/**
 * Convert a real pi session (jsonl) into a test fixture.
 *
 * Extracts the message range of the current conversation about distill
 * prompt testing (user msg "我在测试我写的插件distill" → "多跑有一些吧...")
 * and writes tests/fixtures-real.ts with the entries + fact checklist.
 *
 * Run: bun tests/make-real-fixture.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

const __dirname = dirname(fileURLToPath(import.meta.url));

const SESS_DIR = join(
  homedir(),
  ".pi",
  "agent",
  "sessions",
  "--Users-crack-Crack-pi-extension--",
);
const START_KEYWORD = "我在测试我写的插件distill";
const END_KEYWORD = "多跑有一些吧";

interface RawEntry {
  type: string;
  id: string;
  parentId: string | null;
  timestamp: string;
  [k: string]: unknown;
}

function latestSessionFile(): string {
  const files = readdirSync(SESS_DIR)
    .filter((f) => f.endsWith(".jsonl"))
    .map((f) => join(SESS_DIR, f))
    .sort((a, b) => (a < b ? 1 : -1));
  return files[0];
}

function main() {
  const file = latestSessionFile();
  const lines = readFileSync(file, "utf8").split("\n").filter(Boolean);

  const collected: RawEntry[] = [];
  let started = false;
  let finished = false;

  for (const line of lines) {
    const e = JSON.parse(line) as RawEntry;

    if (!started) {
      if (e.type === "message" && e.message?.role === "user") {
        const text = extractText(e.message.content);
        if (text.includes(START_KEYWORD)) {
          started = true;
          collected.push(e);
        }
      }
      continue;
    }

    // in-range: message entries + distilled-summary custom messages
    if (e.type === "message") {
      collected.push(e);
      if (e.message?.role === "user") {
        const text = extractText(e.message.content);
        if (text.includes(END_KEYWORD)) {
          finished = true;
          break;
        }
      }
    } else if (
      e.type === "custom_message" &&
      (e as { customType?: string }).customType === "distilled-summary"
    ) {
      collected.push(e);
    }
  }

  if (!started) throw new Error(`start keyword not found: ${START_KEYWORD}`);
  if (!finished) throw new Error(`end keyword not found: ${END_KEYWORD}`);

  const userCount = collected.filter(
    (e) => e.type === "message" && e.message?.role === "user",
  ).length;
  const toolCount = collected.filter(
    (e) => e.type === "message" && e.message?.role === "toolResult",
  ).length;
  const summaryCount = collected.filter((e) => e.type === "custom_message").length;

  console.log(
    `extracted ${collected.length} entries (${userCount} user, ${toolCount} toolResult, ${summaryCount} distilled-summary) from ${file}`,
  );

  // Fact checklist for the real conversation.
  const facts = [
    {
      label: "distill动机：上下文过长导致犯蠢、过程噪声多",
      keywords: ["犯蠢", "噪声"],
    },
    {
      label: "压缩原则：结果和错误都要保留",
      keywords: ["错误"],
    },
    {
      label: "v2改进方向：信息分层/金字塔结构/错误教训",
      keywords: ["分层", "金字塔", "教训"],
    },
    {
      label: "403根因：sandbox白名单只有github.com",
      keywords: ["sandbox", "github"],
    },
    {
      label: "解决：白名单加入api.deepseek.com",
      keywords: ["api.deepseek.com", "deepseek"],
    },
    {
      label: "改配置后需重启pi生效",
      keywords: ["重启"],
    },
    {
      label: "测试框架：v1/v2两个模板×多段对话",
      keywords: ["v1", "v2"],
    },
    {
      label: "用户选定方案A：重组结构、提炼要点、删减冗余",
      keywords: ["重组结构", "提炼要点"],
    },
    {
      label: "v1的问题：流水账式罗列",
      keywords: ["流水账", "罗列"],
    },
    {
      label: "用户要求：把当前对话加入长对话测试",
      keywords: ["长对话", "放进测试"],
    },
  ];

  const out = `/**
 * AUTO-GENERATED by tests/make-real-fixture.ts — real conversation fixture.
 * Source session: ${file.split("/").pop()}
 * Range: "${START_KEYWORD}" → "${END_KEYWORD}"
 * Do not edit by hand; re-run the generator to refresh.
 */

export const realFixture = {
  name: "R-long-session",
  scene: "mixed",
  background: [],
  entries: ${JSON.stringify(collected, null, 2)},
  facts: ${JSON.stringify(facts, null, 2)},
};
`;

  writeFileSync(join(__dirname, "fixtures-real.ts"), out);
  console.log("wrote tests/fixtures-real.ts");
}

function extractText(content: unknown): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return (content as Array<{ type?: string; text?: string }>)
    .filter((b) => b?.type === "text" && typeof b.text === "string")
    .map((b) => b.text)
    .join("\n");
}

main();
